#!/bin/sh /etc/rc.common
# See /usr/sbin/chester-at-serialize. procd runs it detached; it waits for
# QModem to finish scanning before the modem sections exist.
START=98
USE_PROCD=1

start_service() {
	procd_open_instance atserialize
	procd_set_param command /usr/sbin/chester-at-serialize 60
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_close_instance
}
