#!/bin/sh /etc/rc.common
# See /usr/sbin/chester-led-power. Runs last and under procd, because it
# has to settle after the services that drive the LEDs have started.
START=99
USE_PROCD=1

start_service() {
	procd_open_instance ledpower
	procd_set_param command /usr/sbin/chester-led-power
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_close_instance
}
