#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Chester >/dev/null 2>&1 || \
	uci batch <<-EOT
		set luci.themes.Chester=/luci-static/chester
		set luci.main.mediaurlbase=/luci-static/chester
		commit luci
	EOT
fi

exit 0
