#!/bin/sh

uci -q set chester.network_defaults=network
[ -n "$(uci -q get chester.network_defaults.optional_wan_mode)" ] || \
	uci -q set chester.network_defaults.optional_wan_mode='wan'
uci -q commit chester

/etc/init.d/chester-optional-wan enable >/dev/null 2>&1 || true

exit 0
