#!/bin/sh

uci -q set chester.modem_cfg_main=modem
uci -q set chester.main=main

if ! uci -q get chester.modem_cfg_main.hidden_lockband >/dev/null 2>&1; then
	uci -q add_list chester.modem_cfg_main.hidden_lockband='UMTS'
fi


uci -q commit chester

exit 0
