#!/bin/sh

mkdir -p /etc/chester-vpn
chmod 700 /etc/chester-vpn

changed_network=0

vpn_proto_from_name() {
	case "$1" in
		vpw[0-9a-f][0-9a-f][0-9a-f][0-9a-f]) echo wireguard ;;
		vpo[0-9a-f][0-9a-f][0-9a-f][0-9a-f]) echo openvpn ;;
		vpl[0-9a-f][0-9a-f][0-9a-f][0-9a-f]) echo l2tp ;;
		vpp[0-9a-f][0-9a-f][0-9a-f][0-9a-f]) echo pptp ;;
	esac
}

for section in $(uci -q show network | sed -n "s/^network\\.\\([^.=]*\\)=interface$/\\1/p"); do
	case "$section" in
		vp[wolpz][0-9a-f][0-9a-f][0-9a-f][0-9a-f]) ;;
		*) continue ;;
	esac

	proto="$(uci -q get network."$section".mvpn_proto)"
	[ -n "$proto" ] || proto="$(uci -q get network."$section".proto)"
	case "$proto" in
		wireguard|openvpn|l2tp|pptp) ;;
		*) proto="$(vpn_proto_from_name "$section")" ;;
	esac
	case "$proto" in
		wireguard|openvpn|l2tp|pptp) ;;
		*) continue ;;
	esac

	[ "$(uci -q get network."$section".mvpn)" = "1" ] || {
		uci set network."$section".mvpn='1'
		changed_network=1
	}
	[ "$(uci -q get network."$section".mvpn_proto)" = "$proto" ] || {
		uci set network."$section".mvpn_proto="$proto"
		changed_network=1
	}
	if [ -z "$(uci -q get network."$section".defaultroute)" ]; then
		uci set network."$section".defaultroute='0'
		changed_network=1
	fi
done

[ "$changed_network" = "1" ] && uci commit network

exit 0
